theme: jekyll-theme-primer
title: meadel's blog
description: 一位程序员的成长之路
show_downloads: false
google_analytics: 
markdown: kramdown
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  math_engine: mathjax
  syntax_highlighter: rouge
